name: HolyFreeze
version: '${project.version}'
main: org.dimasik.holyfreeze.HolyFreeze
api-version: '1.16'
depend:
  - PlaceholderAPI
softdepend:
  - Multiverse-Core
load: POSTWORLD
commands:
  freezing:
    aliases:
      - freeze
    permission: holyfreeze.use
  afkstaff:
    permission: holyfreeze.use
  prova:
    permission: holyfreeze.use